FROM imiell/bad-dockerfile:latest

#Assign environment variables from the Docker build parameters arguments
ARG TWISTCLI_USER=default_value
ARG TWISTCLI_PW=default_value

RUN echo ${TWISTCLI_USER}
RUN echo ${TWISTCLI_PW}

#Download current TwistCLI binary
RUN curl --user ${TWISTCLI_USER}:${TWISTCLI_PW} https://us-east1.cloud.twistlock.com/us-2-158320372/api/v1/util/twistcli > twistcli

RUN chmod a+x twistcli
RUN cat ./twistcli

#Execute image scan from within this container
RUN ./twistcli images scan --details --containerized --address https://us-east1.cloud.twistlock.com/us-2-158320372 --user $TWISTCLI_USER --password $TWISTCLI_PW pcs-log4j-conainerized
